# Maps Python import names to their actual PyPI package names.
# Needed because `import PIL` installs as `Pillow`, etc.

IMPORT_TO_PACKAGE: dict[str, str] = {
    "PIL": "Pillow",
    "cv2": "opencv-python",
    "sklearn": "scikit-learn",
    "skimage": "scikit-image",
    "bs4": "beautifulsoup4",
    "dotenv": "python-dotenv",
    "yaml": "PyYAML",
    "jwt": "PyJWT",
    "dateutil": "python-dateutil",
    "magic": "python-magic",
    "Crypto": "pycryptodome",
    "serial": "pyserial",
    "usb": "pyusb",
    "attr": "attrs",
    "attr_": "attrs",
    "google.cloud": "google-cloud",
    "googleapiclient": "google-api-python-client",
    "httplib2": "httplib2",
    "pkg_resources": "setuptools",
    "setuptools": "setuptools",
    "distutils": "setuptools",
    "gi": "PyGObject",
    "wx": "wxPython",
    "pycurl": "pycurl",
    "MySQLdb": "mysqlclient",
    "psycopg2": "psycopg2",
    "bson": "pymongo",
    "git": "GitPython",
    "boto3": "boto3",
    "botocore": "botocore",
    "Levenshtein": "python-Levenshtein",
    "fitz": "PyMuPDF",
    "docx": "python-docx",
    "pptx": "python-pptx",
    "xlrd": "xlrd",
    "openpyxl": "openpyxl",
    "paramiko": "paramiko",
    "nacl": "PyNaCl",
    "openssl": "pyOpenSSL",
    "OpenSSL": "pyOpenSSL",
    "zmq": "pyzmq",
    "lxml": "lxml",
    "uritools": "uritools",
    "tensorflow": "tensorflow",
    "tf": "tensorflow",
    "torch": "torch",
    "torchvision": "torchvision",
    "torchaudio": "torchaudio",
    "jax": "jax",
    "flax": "flax",
    "transformers": "transformers",
    "datasets": "datasets",
    "huggingface_hub": "huggingface-hub",
    "sentence_transformers": "sentence-transformers",
    "langchain": "langchain",
    "openai": "openai",
    "anthropic": "anthropic",
    "tiktoken": "tiktoken",
    "chromadb": "chromadb",
    "faiss": "faiss-cpu",
    "pinecone": "pinecone-client",
    "weaviate": "weaviate-client",
    "qdrant_client": "qdrant-client",
    "rich": "rich",
    "click": "click",
    "typer": "typer",
    "fastapi": "fastapi",
    "flask": "Flask",
    "django": "Django",
    "starlette": "starlette",
    "uvicorn": "uvicorn",
    "gunicorn": "gunicorn",
    "celery": "celery",
    "redis": "redis",
    "pymongo": "pymongo",
    "motor": "motor",
    "sqlalchemy": "SQLAlchemy",
    "alembic": "alembic",
    "pydantic": "pydantic",
    "httpx": "httpx",
    "aiohttp": "aiohttp",
    "requests": "requests",
    "urllib3": "urllib3",
    "certifi": "certifi",
    "pytest": "pytest",
    "hypothesis": "hypothesis",
    "mypy": "mypy",
    "black": "black",
    "ruff": "ruff",
    "isort": "isort",
    "flake8": "flake8",
    "pylint": "pylint",
    "bandit": "bandit",
    "numpy": "numpy",
    "pandas": "pandas",
    "scipy": "scipy",
    "matplotlib": "matplotlib",
    "seaborn": "seaborn",
    "plotly": "plotly",
    "bokeh": "bokeh",
    "streamlit": "streamlit",
    "gradio": "gradio",
    "loguru": "loguru",
    "tqdm": "tqdm",
    "arrow": "arrow",
    "pendulum": "pendulum",
    "pytz": "pytz",
    "tzdata": "tzdata",
    "toml": "toml",
    "tomllib": "tomli",
    "environ": "django-environ",
    "decouple": "python-decouple",
    "colorama": "colorama",
    "termcolor": "termcolor",
    "blessed": "blessed",
    "textual": "textual",
    "urwid": "urwid",
    "prompt_toolkit": "prompt-toolkit",
    "inquirer": "inquirer",
    "questionary": "questionary",
    "tabulate": "tabulate",
    "prettytable": "PrettyTable",
    "jinja2": "Jinja2",
    "mako": "Mako",
    "markdown": "Markdown",
    "mistune": "mistune",
    "bleach": "bleach",
    "html5lib": "html5lib",
    "pycparser": "pycparser",
    "ply": "ply",
    "pyparsing": "pyparsing",
    "antlr4": "antlr4-python3-runtime",
    "tree_sitter": "tree-sitter",
    "pygments": "Pygments",
    "chardet": "chardet",
    "charset_normalizer": "charset-normalizer",
    "six": "six",
    "future": "future",
    "typing_extensions": "typing-extensions",
    "exceptiongroup": "exceptiongroup",
    "importlib_metadata": "importlib-metadata",
    "zipp": "zipp",
    "wrapt": "wrapt",
    "decorator": "decorator",
    "toolz": "toolz",
    "cytoolz": "cytoolz",
    "more_itertools": "more-itertools",
    "sortedcontainers": "sortedcontainers",
    "interval": "python-interval",
    "bitarray": "bitarray",
    "cryptography": "cryptography",
    "bcrypt": "bcrypt",
    "passlib": "passlib",
    "itsdangerous": "itsdangerous",
    "authlib": "Authlib",
    "oauthlib": "oauthlib",
    "requests_oauthlib": "requests-oauthlib",
    "tweepy": "tweepy",
    "slack_sdk": "slack-sdk",
    "discord": "discord.py",
    "telethon": "Telethon",
    "boto": "boto",
    "s3fs": "s3fs",
    "gcsfs": "gcsfs",
    "adlfs": "adlfs",
    "fsspec": "fsspec",
    "dask": "dask",
    "ray": "ray",
    "joblib": "joblib",
    "multiprocess": "multiprocess",
    "concurrent": "futures",
    "psutil": "psutil",
    "py": "py",
    "pywin32": "pywin32",
    "winreg": "winreg",
    "win32api": "pywin32",
    "comtypes": "comtypes",
    "pyautogui": "PyAutoGUI",
    "pynput": "pynput",
    "pyperclip": "pyperclip",
    "plyer": "plyer",
    "desktop_notifier": "desktop-notifier",
    "notify2": "notify2",
    "schedule": "schedule",
    "apscheduler": "APScheduler",
    "crontab": "python-crontab",
    "watchdog": "watchdog",
    "inotify": "inotify",
    "pyinotify": "pyinotify",
    "Xlib": "python-xlib",
    "pydbus": "pydbus",
    "dbus": "dbus-python",
    "appkit": "pyobjc-framework-Cocoa",
    "foundation": "pyobjc-framework-Cocoa",
    "cocoa": "pyobjc-framework-Cocoa",
    "objc": "pyobjc-core",
}

# Python standard library modules — skip checking these
STDLIB_MODULES: frozenset[str] = frozenset({
    "__future__", "_thread", "abc", "aifc", "argparse", "array",
    "ast", "asynchat", "asyncio", "asyncore", "atexit", "audioop",
    "base64", "bdb", "binascii", "binhex", "bisect", "builtins",
    "bz2", "calendar", "cgi", "cgitb", "chunk", "cmath", "cmd",
    "code", "codecs", "codeop", "collections", "colorsys", "compileall",
    "concurrent", "configparser", "contextlib", "contextvars", "copy",
    "copyreg", "cProfile", "csv", "ctypes", "curses", "dataclasses",
    "datetime", "dbm", "decimal", "difflib", "dis", "doctest",
    "email", "encodings", "enum", "errno", "faulthandler", "fcntl",
    "filecmp", "fileinput", "fnmatch", "fractions", "ftplib",
    "functools", "gc", "getopt", "getpass", "gettext", "glob",
    "grp", "gzip", "hashlib", "heapq", "hmac", "html", "http",
    "idlelib", "imaplib", "imghdr", "importlib", "inspect", "io",
    "ipaddress", "itertools", "json", "keyword", "lib2to3", "linecache",
    "locale", "logging", "lzma", "mailbox", "mailcap", "marshal",
    "math", "mimetypes", "mmap", "modulefinder", "multiprocessing",
    "netrc", "nis", "nntplib", "numbers", "operator", "optparse",
    "os", "ossaudiodev", "parser", "pathlib", "pdb", "pickle",
    "pickletools", "pipes", "pkgutil", "platform", "plistlib",
    "poplib", "posix", "posixpath", "pprint", "profile", "pstats",
    "pty", "pwd", "py_compile", "pyclbr", "pydoc", "queue",
    "quopri", "random", "re", "readline", "reprlib", "resource",
    "rlcompleter", "runpy", "sched", "secrets", "select", "selectors",
    "shelve", "shlex", "shutil", "signal", "site", "smtpd", "smtplib",
    "sndhdr", "socket", "socketserver", "spwd", "sqlite3", "sre_compile",
    "sre_constants", "sre_parse", "ssl", "stat", "statistics", "string",
    "stringprep", "struct", "subprocess", "sunau", "symtable", "sys",
    "sysconfig", "syslog", "tabnanny", "tarfile", "telnetlib", "tempfile",
    "termios", "test", "textwrap", "threading", "time", "timeit",
    "tkinter", "token", "tokenize", "tomllib", "trace", "traceback",
    "tracemalloc", "tty", "turtle", "turtledemo", "types", "typing",
    "unicodedata", "unittest", "urllib", "uu", "uuid", "venv",
    "warnings", "wave", "weakref", "webbrowser", "winreg", "winsound",
    "wsgiref", "xdrlib", "xml", "xmlrpc", "zipapp", "zipfile",
    "zipimport", "zlib", "zoneinfo", "_collections_abc", "_weakrefset",
    "abc", "typing_extensions",
})
